"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ConnectionProvider, WalletProvider } from "@solana/wallet-adapter-react";
import { clusterApiUrl } from "@solana/web3.js";
import { WalletModalProvider, WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import { PhantomWalletAdapter } from "@solana/wallet-adapter-phantom";
import "@solana/wallet-adapter-react-ui/styles.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const endpoint=clusterApiUrl("devnet");
  const phantomWallet=new PhantomWalletAdapter();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <ConnectionProvider endpoint={endpoint} >
            <WalletProvider wallets={[phantomWallet]}>
              <WalletModalProvider>
                {/* <WalletMultiButton/> */}
                <Navbar/>
                {children}
              </WalletModalProvider>
            </WalletProvider>
          </ConnectionProvider>
        </div>
        </body>
    </html>
  );
}
